const ShopActionsTypes = {
  GET_COLLECTIONS: "GET_COLLECTIONS",
  GET_COLLECTIONS_SUCCESS: "GET_COLLECTIONS_SUCCESS",
  GET_COLLECTIONS_FAILURE: "GET_COLLECTIONS_FAILURE"
};

export default ShopActionsTypes;
