const UserActionTypes = {
	SET_CURRENT_USER: 'SET_CURRENT_USER',
	GOOGLE_SING_IN_START: 'GOOGLE_SING_IN_START',
	SING_IN_SUCCESS: 'SING_IN_SUCCESS',
	SING_IN_FAILURE: 'SING_IN_FAILURE',
	EMAIL_SIGN_IN_START: 'EMAIL_SIGN_IN_START'
};

export default UserActionTypes;
