const UserActionTypes = {
  SET_CURRENT_USER: "SET_CURRENT_USER",
  GOOGLE_SING_IN_START: "GOOGLE_SING_IN_START",
  GOOGLE_SING_IN_SUCCESS: "GOOGLE_SING_IN_SUCCESS",
  GOOGLE_SING_IN_FAILURE: "GOOGLE_SING_IN_FAILURE",
  EMAIL_SIGN_IN_START: "EMAIL_SIGN_IN_START",
  EMAIL_SIGN_IN_SUCCESS: "EMAIL_SIGN_IN_SUCCESS",
  EMAIL_SIGN_IN_FAILURE: "EMAIL_SIGN_IN_FAILURE"
};

export default UserActionTypes;
